gcc nq.c -Ofast -march=native -mtune=native -Wall -Wno-unused -pipe -onq -DSILENCE -DNOFILEINPUT -DNOFILEOUTPUT -DNOPRINTBOARD -DNOINTEGRITY -DNOVERIFIER -DNOPRESOLVED -DNDEBUG -DNOSYNTAX
time ./nq 100000000 1s

